<?php

/**
 * ContentTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContentTable extends Doctrine_Table
{

    const CONTENT_AUDIO = 'audio';

    const CONTENT_VIDEO = 'video';

    const CONTENT_TEXT = 'text';

    const CONTENT_IMAGE = 'image';

    public static $types = array(self::CONTENT_AUDIO, self::CONTENT_TEXT, self::CONTENT_VIDEO, self::CONTENT_IMAGE);

    /**
     * Returns an instance of this class.
     *
     * @return object ContentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Content');
    }

    public function getAllChronologicalQuery(Doctrine_Query $q = null)
    {
        if (is_null($q))
        {
            $q = $this->createQuery('c');
        }
        $alias = $q->getRootAlias();

        $q->leftJoin($alias.'.Comments co')
          ->orderBy($alias.'.date_published DESC');
        return $q;
    }

    public function getLatestChronologicalExcept(array $ids, $return_as_json=false)
    {
        $q = $this->getAllChronologicalQuery(null);
        $new_contents = $q->whereNotIn($q->getRootAlias().'.id', $ids)->limit(1)->fetchOne();
        if ($new_contents)
        {
            if ($return_as_json)
            {
                return json_encode($new_contents->toArray());
            }
            return $new_contents;

        }
        return false;
    }
    public function getAllChronological()
    {
        return $this->getAllChronologicalQuery(null)->execute();

    }

    public function getWithComments($content_id)
    {
        $q = $this->createQuery('c')
            ->leftJoin('c.Comments cm')
            ->where('c.id = ?', $content_id);
        return $q->fetchOne();
    }
}