<?php

/**
 * ContentVideoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContentVideoTable extends ContentTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContentVideoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ContentVideo');
    }
}