<?php

/**
 * ContentImageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContentImageTable extends ContentTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContentImageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ContentImage');
    }
}