<?php

/**
 * ContentText
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    octolowbar
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ContentText extends BaseContentText
{
    public function getType()
    {
        return ContentTable::CONTENT_TEXT;
    }
}
