<?php

/**
 * ContentAudioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContentAudioTable extends ContentTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContentAudioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ContentAudio');
    }
}