<?php

/**
 * ContentTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Content');
    }

    public function getAllChronological()
    {
        $q = $this->createQuery('c')
            ->orderBy('c.date_published DESC');
        return $q->execute();

    }

    public function getWithComments($content_id)
    {
        $q = $this->createQuery('c')
            ->leftJoin('c.Comments cm')
            ->where('c.id = ?', $content_id);
        return $q->fetchOne();
    }
}