# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: timeline, action: index }

show_content:
  url:   /timeline/show/:id
  param: { module: timeline, action: show }

add_content_type:
  url:   /timeline/add/:content_type
  param: { module: timeline, action: add }

add_content:
  url:   /timeline/add
  param: { module: timeline, action: add }

add_content_video:
  url:   /timeline/add/video
  param: { module: timeline, action: addVideo }

add_content_audio:
  url:   /timeline/add/audio
  param: { module: timeline, action: addAudio }

add_content_image:
  url:   /timeline/add/image
  param: { module: timeline, action: addImage }

add_content_text:
  url:   /timeline/add/text
  param: { module: timeline, action: addText }

process_comment:
  url: /timeline/comment/add
  param: { module: timeline, action addComment }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
